import os
from dotenv import load_dotenv
load_dotenv()

TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY")
MONGODB_URL = os.getenv("MONGODB_URL")
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
PLAY_HT_USER_ID=os.getenv("PLAY_HT_USER_ID")
PLAY_HT_API_KEY=os.getenv("PLAY_HT_API_KEY")


DB_NAME_POSTGRES = os.getenv("DB_NAME_POSTGRES")
DB_USER_POSTGRES = os.getenv("DB_USER_POSTGRES")
DB_PASSWORD_POSTGRES = os.getenv("DB_PASSWORD_POSTGRES")
DB_HOST_POSTGRES = os.getenv("POSTGRES_HOST_DOCKER")
DB_PORT_POSTGRES = os.getenv("POSTGRES_PORT_DOCKER")
POSTGRES_DB = os.getenv("POSTGRES_DB")